name: quant
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - plotly
  - numpy
  - sqlite
  - pandas
  - tqdm
  - beautifulsoup4
  - requests
  - matplotlib-inline
  - matplotlib
  - ipykernel
  - ipywidgets
  - loguru
  - python-dotenv
  - pydantic
  - orjson
  - lxml
